/**
 * Coxeter Group for Hyperbolic Honeycombs
 *
 * Computes the reflection mirrors and fundamental domain for a {p,q,r} honeycomb.
 * The honeycomb is generated by a rank-4 Coxeter group with 4 reflection mirrors.
 */

import { type Vec4, hdot, hnormalize, vec4 } from '../math/minkowski'

/**
 * Coxeter group data for a {p,q,r} honeycomb.
 */
export interface CoxeterGroup {
  /** The four reflection mirrors A, B, C, D */
  mirrors: [Vec4, Vec4, Vec4, Vec4]

  /** Initial vertex position (on hyperboloid) */
  vertex: Vec4

  /** Schlafli indices [AB, AC, AD, BC, BD, CD] */
  schlafli: [number, number, number, number, number, number]
}

/**
 * Initialize a Coxeter group for a {p,q,r} honeycomb.
 *
 * The Coxeter diagram for {p,q,r} is:
 *   A --p-- B --q-- C --r-- D
 *
 * With orthogonal pairs: A-C, A-D, B-D (index 2).
 *
 * @param p - Polygon sides (number of edges per face)
 * @param q - Vertex figure (polygons meeting at each edge of a cell)
 * @param r - Edge figure (cells meeting at each edge)
 * @param activeMirrors - Which mirrors define the initial vertex [a,b,c,d]
 */
export function initCoxeterGroup(
  p: number,
  q: number,
  r: number,
  activeMirrors: [number, number, number, number] = [1, 0, 0, 0],
): CoxeterGroup {
  // Map {p,q,r} to Coxeter diagram indices
  const AB = p
  const AC = 2 // Orthogonal
  const AD = 2 // Orthogonal
  const BC = q
  const BD = 2 // Orthogonal
  const CD = r

  // Cosines of dihedral angles (negative for inward-facing mirrors)
  const c01 = -Math.cos(Math.PI / AB)
  const c02 = -Math.cos(Math.PI / AC)
  const c03 = -Math.cos(Math.PI / AD)
  const c12 = -Math.cos(Math.PI / BC)
  const c13 = -Math.cos(Math.PI / BD)
  const c23 = -Math.cos(Math.PI / CD)

  // Compute mirror normals using Gram-Schmidt-like construction

  // Mirror A: along x-axis
  const A: Vec4 = vec4(1, 0, 0, 0)

  // Mirror B: makes angle arccos(c01) with A
  const B: Vec4 = vec4(c01, Math.sqrt(1 - c01 * c01), 0, 0)

  // Mirror C: determined by angles with A and B
  const C: Vec4 = vec4(c02, 0, 0, 0)
  C.y = (c12 - C.x * B.x) / B.y
  C.z = Math.sqrt(Math.abs(1 - C.x * C.x - C.y * C.y))

  // Mirror D: in 4D, with negative w for upper hyperboloid sheet
  const D: Vec4 = vec4(c03, 0, 0, 0)
  D.y = (c13 - D.x * B.x) / B.y
  D.z = (c23 - (D.x * C.x + D.y * C.y)) / C.z
  D.w = -Math.sqrt(Math.abs(D.x * D.x + D.y * D.y + D.z * D.z - 1))

  const mirrors: [Vec4, Vec4, Vec4, Vec4] = [A, B, C, D]

  // Compute initial vertex from active mirrors
  // The vertex is at the intersection of the active mirror planes
  const vertex = computeVertex(mirrors, activeMirrors)

  return {
    mirrors,
    vertex,
    schlafli: [AB, AC, AD, BC, BD, CD],
  }
}

/**
 * Compute the vertex position from active mirrors.
 * The vertex is defined as a linear combination of mirror normals,
 * weighted by the activeMirrors coefficients.
 */
function computeVertex(
  mirrors: [Vec4, Vec4, Vec4, Vec4],
  activeMirrors: [number, number, number, number],
): Vec4 {
  const [A, B, C, D] = mirrors
  const [a, b, c, d] = activeMirrors

  // Apply the Minkowski metric signature to get dual vectors
  const H = vec4(1, 1, 1, -1)
  const HA = vec4(H.x * A.x, H.y * A.y, H.z * A.z, H.w * A.w)
  const HB = vec4(H.x * B.x, H.y * B.y, H.z * B.z, H.w * B.w)
  const HC = vec4(H.x * C.x, H.y * C.y, H.z * C.z, H.w * C.w)
  const HD = vec4(H.x * D.x, H.y * D.y, H.z * D.z, H.w * D.w)

  // Build the Gram matrix and invert it
  const M = [
    [hdot(A, HA), hdot(B, HA), hdot(C, HA), hdot(D, HA)],
    [hdot(A, HB), hdot(B, HB), hdot(C, HB), hdot(D, HB)],
    [hdot(A, HC), hdot(B, HC), hdot(C, HC), hdot(D, HC)],
    [hdot(A, HD), hdot(B, HD), hdot(C, HD), hdot(D, HD)],
  ]

  const Minv = invert4x4(M)
  if (!Minv) {
    // Fallback to origin if matrix is singular
    return vec4(0, 0, 0, 1)
  }

  // Compute vertex as weighted combination
  const v = vec4(
    a * Minv[0][0] + b * Minv[0][1] + c * Minv[0][2] + d * Minv[0][3],
    a * Minv[1][0] + b * Minv[1][1] + c * Minv[1][2] + d * Minv[1][3],
    a * Minv[2][0] + b * Minv[2][1] + c * Minv[2][2] + d * Minv[2][3],
    a * Minv[3][0] + b * Minv[3][1] + c * Minv[3][2] + d * Minv[3][3],
  )

  // Transform back through mirror normals
  const result = vec4(
    v.x * A.x + v.y * B.x + v.z * C.x + v.w * D.x,
    v.x * A.y + v.y * B.y + v.z * C.y + v.w * D.y,
    v.x * A.z + v.y * B.z + v.z * C.z + v.w * D.z,
    v.x * A.w + v.y * B.w + v.z * C.w + v.w * D.w,
  )

  return hnormalize(result)
}

/**
 * Invert a 4x4 matrix (for computing vertex from active mirrors).
 */
function invert4x4(m: number[][]): number[][] | null {
  const n = 4
  const a = m.map(row => [...row])
  const inv = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
  ]

  for (let col = 0; col < n; col++) {
    // Find pivot
    let maxRow = col
    for (let row = col + 1; row < n; row++) {
      if (Math.abs(a[row][col]) > Math.abs(a[maxRow][col])) {
        maxRow = row
      }
    }

    // Swap rows
    ;[a[col], a[maxRow]] = [a[maxRow], a[col]]
    ;[inv[col], inv[maxRow]] = [inv[maxRow], inv[col]]

    // Check for singular matrix
    if (Math.abs(a[col][col]) < 1e-10) {
      return null
    }

    // Scale pivot row
    const scale = 1 / a[col][col]
    for (let j = 0; j < n; j++) {
      a[col][j] *= scale
      inv[col][j] *= scale
    }

    // Eliminate column
    for (let row = 0; row < n; row++) {
      if (row !== col) {
        const factor = a[row][col]
        for (let j = 0; j < n; j++) {
          a[row][j] -= factor * a[col][j]
          inv[row][j] -= factor * inv[col][j]
        }
      }
    }
  }

  return inv
}

/**
 * Check if {p,q,r} defines a valid hyperbolic honeycomb.
 */
export function isHyperbolicHoneycomb(
  p: number,
  q: number,
  r: number,
): boolean {
  return 1 / p + 1 / q + 1 / r < 1
}

/**
 * Check if {p,q,r} has compact (finite) polyhedral cells.
 * Cells are {p,q} polyhedra, which are finite only when (p-2)(q-2) < 4.
 */
export function isCompactHoneycomb(
  p: number,
  q: number,
): boolean {
  return (p - 2) * (q - 2) < 4
}

/**
 * Check if {p,q} cells have ideal vertices ((p-2)(q-2) = 4)
 * or ultra-ideal vertices ((p-2)(q-2) > 4).
 */
export function hasIdealVertices(
  p: number,
  q: number,
): boolean {
  return (p - 2) * (q - 2) >= 4
}

/**
 * Get descriptive name for a honeycomb.
 */
export function honeycombName(p: number, q: number, r: number): string {
  const cellNames: Record<string, string> = {
    '3,3': 'tetrahedral',
    '4,3': 'cubic',
    '5,3': 'dodecahedral',
    '3,4': 'octahedral',
    '3,5': 'icosahedral',
  }
  const cell = cellNames[`${p},${q}`] || `{${p},${q}}`
  return `${cell} {${p},${q},${r}}`
}
